source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

def import_pods
    pod 'SVProgressHUD', '~> 2.1.2'
end

target 'PlugPagCafe-Swift' do
    import_pods
end
